@echo off

@if not exist "../build" (
    echo Do initial setup first

    exit /b 1
)

chdir ../build

cmake .. ^
   -DCMAKE_BUILD_TYPE=Release ^
   -DENABLE_INTEL_CPU=ON ^
   -DENABLE_INTEL_GPU=ON ^
   -DENABLE_INTEL_NPU=OFF ^
   -DENABLE_AUTO=OFF ^
   -DENABLE_MULTI=OFF ^
   -DENABLE_HETERO=OFF ^
   -DENABLE_AUTO_BATCH=OFF ^
   -DENABLE_TEMPLATE=OFF ^
   -DENABLE_SAMPLES=ON ^
   -DENABLE_PROXY=OFF ^
   -DENABLE_TESTS=OFF ^
   -DENABLE_PYTHON=OFF ^
   -DENABLE_OV_PADDLE_FRONTEND=OFF ^
   -DENABLE_OV_ONNX_FRONTEND=ON ^
   -DENABLE_OV_IR_FRONTEND=OFF ^
   -DENABLE_OV_TF_FRONTEND=OFF ^
   -DENABLE_OV_TF_LITE_FRONTEND=OFF ^
   -DENABLE_OV_PYTORCH_FRONTEND=OFF ^
   -DBUILD_SAMPLE_NAME=benchmark_app ^
   -DENABLE_OV_JAX_FRONTEND=OFF ^
   -DENABLE_FUNCTIONAL_TESTS=OFF ^
   -DENABLE_WHEEL=OFF ^
   -DENABLE_DOCS=OFF ^
   -DENABLE_FASTER_BUILD=ON ^
   -DSELECTIVE_BUILD=ON ^
   -DENABLE_PROFILING_ITT=OFF ^
   -DSELECTIVE_BUILD_STAT="%~dp0\openvino_2026_1_collect\stats\*.csv" ^
   -DBUILD_SHARED_LIBS=ON ^
   -DENABLE_ONEDNN_FOR_GPU=OFF

cmake --build . --config Release -j8